SEED = 12345
DEVICE = 'cuda:0'

params = {
    "N0_root": {
        'booster': ['gbtree'],
        'objective': ['multi:softmax'],
        'num_class': [7],
        'eval_metric': ['mlogloss'],
        'learning_rate': [0.3],
        'n_estimators': [100],
        'max_depth': [8],
        'min_child_weight': [3],
        'gamma': [0.001],
        'subsample': [1],
        'colsample_bytree': [1],
        'reg_alpha': [0.00005],
        'seed': [SEED],
        'device': [DEVICE]
    },
    "N1_Crimes Contra Pessoa": {
        'booster': ['gbtree'],
        'objective': ['multi:softmax'],
        'num_class': [5],
        'eval_metric': ['mlogloss'],
        'learning_rate': [0.2],
        'n_estimators': [100],
        'max_depth': [5],
        'min_child_weight': [4],
        'gamma': [1e-06],
        'subsample': [0.5],
        'colsample_bytree': [1],
        'reg_alpha': [0.00015],
        'seed': [SEED],
        'device': [DEVICE]
    },
    "N1_Crimes Contra Propriedade": {
        'booster': ['gbtree'],
        'objective': ['multi:softmax'],
        'num_class': [5],
        'eval_metric': ['mlogloss'],
        'learning_rate': [0.4],
        'n_estimators': [100],
        'max_depth': [6],
        'min_child_weight': [3],
        'gamma': [0.02],
        'subsample': [0.6],
        'colsample_bytree': [0.4],
        'reg_alpha': [5e-05],
        'seed': [SEED],
        'device': [DEVICE]
    },
    "N1_Crimes de Trânsito ou Meio Ambiente": {
        'booster': ['gbtree'],
        'objective': ['multi:softmax'],
        'num_class': [3],
        'eval_metric': ['mlogloss'],
        'learning_rate': [0.2],
        'n_estimators': [100],
        'max_depth': [3],
        'min_child_weight': [4],
        'gamma': [1e-06],
        'subsample': [0.4],
        'colsample_bytree': [0.5],
        'reg_alpha': [0.0001],
        'seed': [SEED],
        'device': [DEVICE]
    },
    "N1_Recuperação de Veículo ou Atos Administrativos ou Registro de Acontecimentos": {
        'booster': ['gbtree'],
        'objective': ['multi:softmax'],
        'num_class': [3],
        'eval_metric': ['mlogloss'],
        'learning_rate': [0.2],
        'n_estimators': [100],
        'max_depth': [7],
        'min_child_weight': [4],
        'gamma': [0.02],
        'subsample': [0.5],
        'colsample_bytree': [1],
        'reg_alpha': [1e-05],
        'seed': [SEED],
        'device': [DEVICE]
    },
    "N1_Relacionados a Drogas, Entorpecentes e Porte de Armas": {
        'booster': ['gbtree'],
        'objective': ['multi:softmax'],
        'num_class': [6],
        'eval_metric': ['mlogloss'],
        'learning_rate': [0.155],
        'n_estimators': [100],
        'max_depth': [4],
        'min_child_weight': [2],
        'gamma': [1e-05],
        'subsample': [0.5],
        'colsample_bytree': [0.3],
        'reg_alpha': [1e-05],
        'seed': [SEED],
        'device': [DEVICE]
    },
    "N1_Resistência, Desacato ou Desobediência": {
        'booster': ['gbtree'],
        'objective': ['multi:softmax'],
        'num_class': [4],
        'eval_metric': ['mlogloss'],
        'learning_rate': [0.2],
        'n_estimators': [100],
        'max_depth': [3],
        'min_child_weight': [2],
        'gamma': [1e-05],
        'subsample': [0.5],
        'colsample_bytree': [0.1],
        'reg_alpha': [1e-05],
        'seed': [SEED],
        'device': [DEVICE]
    },
    "N1_Violação ou Perturbação ou Dano ou Exercício Arbitrário": {
        'booster': ['gbtree'],
        'objective': ['multi:softmax'],
        'num_class': [4],
        'eval_metric': ['mlogloss'],
        'learning_rate': [0.2],
        'n_estimators': [100],
        'max_depth': [4],
        'min_child_weight': [2],
        'gamma': [1e-05],
        'subsample': [0.5],
        'colsample_bytree': [0.5],
        'reg_alpha': [5e-05],
        'seed': [SEED],
        'device': [DEVICE]
    },
    "N2_Ameaça ou Injúria ou Perseguição ou Dano ou Extorsão": {
        'booster': ['gbtree'],
        'objective': ['multi:softmax'],
        'num_class': [8],
        'eval_metric': ['mlogloss'],
        'learning_rate': [0.1],
        'n_estimators': [100],
        'max_depth': [5],
        'min_child_weight': [2],
        'gamma': [1e-05],
        'subsample': [0.5],
        'colsample_bytree': [0.5],
        'reg_alpha': [0.001],
        'seed': [SEED],
        'device': [DEVICE]
    },
    "N2_Atos Administrativos": {
        'booster': ['gbtree'],
        'objective': ['multi:softmax'],
        'num_class': [7],
        'eval_metric': ['mlogloss'],
        'learning_rate': [0.2],
        'n_estimators': [100],
        'max_depth': [4],
        'min_child_weight': [2],
        'gamma': [0.001],
        'subsample': [0.4],
        'colsample_bytree': [0.1],
        'reg_alpha': [5e-05],
        'seed': [SEED],
        'device': [DEVICE]
    },
    "N2_Estelionato": {
        'booster': ['gbtree'],
        'objective': ['multi:softmax'],
        'num_class': [3],
        'eval_metric': ['mlogloss'],
        'learning_rate': [0.2],
        'n_estimators': [100],
        'max_depth': [5],
        'min_child_weight': [3],
        'gamma': [0.001],
        'subsample': [0.6],
        'colsample_bytree': [1],
        'reg_alpha': [0.0001],
        'seed': [SEED],
        'device': [DEVICE]
    },
    "N2_Estupro": {
        'booster': ['gbtree'],
        'objective': ['multi:softmax'],
        'num_class': [2],
        'eval_metric': ['mlogloss'],
        'learning_rate': [0.2],
        'n_estimators': [100],
        'max_depth': [5],
        'min_child_weight': [3],
        'gamma': [0.01],
        'subsample': [0.6],
        'colsample_bytree': [0.5],
        'reg_alpha': [1e-05],
        'seed': [SEED],
        'device': [DEVICE]
    },
    "N2_Furto": {
        'booster': ['gbtree'],
        'objective': ['multi:softmax'],
        'num_class': [12],
        'eval_metric': ['mlogloss'],
        'learning_rate': [0.1],
        'n_estimators': [100],
        'max_depth': [5],
        'min_child_weight': [2],
        'gamma': [0.001],
        'subsample': [0.5],
        'colsample_bytree': [0.1],
        'reg_alpha': [5e-05],
        'seed': [SEED],
        'device': [DEVICE]
    },
    "N2_Homicídio": {
        'booster': ['gbtree'],
        'objective': ['multi:softmax'],
        'num_class': [2],
        'eval_metric': ['mlogloss'],
        'learning_rate': [0.1],
        'n_estimators': [100],
        'max_depth': [5],
        'min_child_weight': [3],
        'gamma': [1e-05],
        'subsample': [0.4],
        'colsample_bytree': [0.1],
        'reg_alpha': [1e-05],
        'seed': [SEED],
        'device': [DEVICE]
    },
    "N2_Lesão Corporal": {
        'booster': ['gbtree'],
        'objective': ['multi:softmax'],
        'num_class': [7],
        'eval_metric': ['mlogloss'],
        'learning_rate': [0.1],
        'n_estimators': [100],
        'max_depth': [4],
        'min_child_weight': [2],
        'gamma': [0.001],
        'subsample': [0.6],
        'colsample_bytree': [0.1],
        'reg_alpha': [1e-05],
        'seed': [SEED],
        'device': [DEVICE]
    },
    "N2_Recuperação de Veículo": {
        'booster': ['gbtree'],
        'objective': ['multi:softmax'],
        'num_class': [2],
        'eval_metric': ['mlogloss'],
        'learning_rate': [0.1],
        'n_estimators': [100],
        'max_depth': [7],
        'min_child_weight': [6],
        'gamma': [0.001],
        'subsample': [0.6],
        'colsample_bytree': [0.4],
        'reg_alpha': [5e-05],
        'seed': [SEED],
        'device': [DEVICE]
    },
    "N2_Registro de Um Acontecimento": {
        'booster': ['gbtree'],
        'objective': ['multi:softmax'],
        'num_class': [7],
        'eval_metric': ['mlogloss'],
        'learning_rate': [0.2],
        'n_estimators': [100],
        'max_depth': [5],
        'min_child_weight': [2],
        'gamma': [0.001],
        'subsample': [0.5],
        'colsample_bytree': [0.1],
        'reg_alpha': [0.0001],
        'seed': [SEED],
        'device': [DEVICE]
    },
    "N2_Roubo": {
        'booster': ['gbtree'],
        'objective': ['multi:softmax'],
        'num_class': [10],
        'eval_metric': ['mlogloss'],
        'learning_rate': [0.1],
        'n_estimators': [100],
        'max_depth': [5],
        'min_child_weight': [3],
        'gamma': [0.0001],
        'subsample': [0.4],
        'colsample_bytree': [1],
        'reg_alpha': [0.0001],
        'seed': [SEED],
        'device': [DEVICE]
    }
}
